### ISSUE TITLE
Run 'make clean' as part of 'mix clean'

### ISSUE THREAD

**Issue by fhunleth** [elixir-lang/elixir_make#2]
What are the thoughts on invoking `make clean` to clean up the object files and binaries it creates as part of `mix clean`? I would expect most `Makefiles` to have a `clean` target since it's standard practice.

**Comment by whatyouhide** [comment]
@fhunleth this can be achieved with the `:make_targets` option though, right?

**Comment by josevalim** [comment]
@whatyouhide it is not before we compile but when we call "mix clean". I
think we should uppity it, yeah.

On Sunday, May 15, 2016, Andrea Leopardi <notifications@github.com> wrote:

> @fhunleth <https://github.com/fhunleth> this can be achieved with the
> :make_targets option though, right?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir_make/issues/2#issuecomment-219291481>
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by josevalim** [comment]
Uppity -> support it. Thanks autocomplete.

On Sunday, May 15, 2016, José Valim <jose.valim@plataformatec.com.br> wrote:

> @whatyouhide it is not before we compile but when we call "mix clean". I
> think we should uppity it, yeah.
>
> On Sunday, May 15, 2016, Andrea Leopardi <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> @fhunleth <https://github.com/fhunleth> this can be achieved with the
>> :make_targets option though, right?
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/elixir-lang/elixir_make/issues/2#issuecomment-219291481>
>>
>
>
> --
>
>
> *José Valim*
> www.plataformatec.com.br
> Skype: jv.ptec
> Founder and Director of R&D
>
>

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by whatyouhide** [comment]
@josevalim ok, I see. Then maybe we can add a `make_clean: boolean` option so that we don't run it blindly on `mix clean`. Wdyt?

**Comment by josevalim** [comment]
@whatyouhide maybe `make_clean: ["clean"]`. If it is not specified, we don't clean anything?

**Comment by josevalim** [comment]
@whatyouhide maybe `make_clean: ["clean"]`. If it is not specified, we don't clean anything?

**Comment by whatyouhide** [comment]
@josevalim yeah, sounds good.

**Comment by fhunleth** [comment]
Thanks!!!
