### ISSUE TITLE
Run make on an erlang dependency? 

### ISSUE THREAD

**Issue by gdub01** [elixir-lang/elixir_make#20]
I'm trying to include https://github.com/chitika/cberl as an app dependency in my mix file. It's an erlang lib with NIFs for couchbase with a makefile. 

The makefile in that erlang lib doesn't seem to be run under a normal mix compile... 

I tried adding this lib with this setup:

     make_makefile: "../../deps/cberl/Makefile",
     compilers: [:elixir_make] ++ Mix.compilers,

And it tried to run. However it's looking for rebar in the wrong spot: 

'.../apps/couchbase/rebar get-deps'
'.../apps/couchbase/rebar: No such file or directory'

I'm probably going about this all wrong =) Do you know a good way to run make on an erlang dependency? Or really any dependency I guess?

**Comment by josevalim** [comment]
You cannot use this library to compile dependencies. It is about the current project. It seems that project can be used as rebar2 dependency, so I would depend on it as usual and pass `manager: :rebar` to make sure you try to use with the proper rebar version. If it doesn't work, I would recommend looking for help on the elixirforum.
