### ISSUE TITLE
Please drop a new release

### ISSUE THREAD

**Issue by cdegroot** [elixir-lang/elixir_make#24]
It's not a super big thing, but I want to do a full, hex-based, integration test of a project I'm working on; the project relies on the PR that got merged in. 

So I don't want to chase people into action or something, but is there a plan to release a new version shortly? If not, I'll probably want to spend some time on a work-around for my end-to-end test but that's fine; would just like to hear about timelines :)

TIA,

Cees

**Comment by whatyouhide** [comment]
Done! v0.4.2 is out. https://hex.pm/packages/elixir_make/0.4.2

**Comment by cdegroot** [comment]
Lol, that was fast. First a PR closed in hours, now this. You guys are spoiling me. I owe :beer: if I ever manage to bump into you at a confierence.
