### ISSUE TITLE
elixir_make with Nerves on Elixir 1.8  

### ISSUE THREAD

**Issue by ConnorRigby** [elixir-lang/elixir_make#26]
With the introduction of `Mix.target()`, nerves now stores built dependencies in the same directory for all targets, `make` will not pick up changes between targets. [here](https://github.com/ConnorRigby/elixir-make-example) is an example.

in the `main_app` Nerves application we have a dependency on `c_library`. 
* Call `MIX_TARGET=rpi0 mix deps.get`
* Call `MIX_TARGET=rpi0 mix firmware`
* `c_library` gets compiled twice.
* `make` sees that `c_library.c` hasn't changed.
* `make` doesn't recompile `priv/c_library` 
* `priv/c_library` is compiled for x86, _not_ ARM.

**Comment by ConnorRigby** [comment]
> I believe it is an issue that exists before v1.8

It was an issue before 1.8, but it was much more edge case than it is now. Before this only happened for `path: ` dependencies, now it happens regardless of method of fetching the dependency. 

There are a number of options, but ideally it would be one that wouldn't require updating `makefile`s of projects since it would require updating a lot of mix projects.

One problem with the suggested solution is that the Nerves tooling looks at _every_ file in the `priv` directory, so if there is for example `priv/c_library-host` and `priv/c_library-rpi0` both of those files would be linted, and the incorrect one would cause an error.

I haven't fully formed a better solution yet. I'm reading through how the `priv` directory is handled by `elixir` right now to better understand why it's happening before suggesting other solutions.

**Comment by josevalim** [comment]
@ConnorRigby are those projects setting the `make_clean` configuration at least? If so, we can try to work with that... but then it means cleaning every time the target changes. It would be nice to cache it.

**Comment by fhunleth** [comment]
Update: I've updated the Makefile in the project above to create object files (there really wasn't a good reason for it not to). The object files get stored under `_build`, but don't get included in the release. I've also rearranged the file and updated its naming to be closer to Makefiles in other Elixir projects. Barring comments, I'm tempted to push these updates out to see how they work more broadly and then iterate.

**Comment by fhunleth** [comment]
I've been incrementally updating `mix.exs` and `Makefiles` for Nerves projects. Things seem to be working out well with using `MIX_COMPILE_PATH` to derive paths to storing object files and the final executables and shared libraries. I think this can be closed. @ConnorRigby - what do you think?

**Comment by ConnorRigby** [comment]
I haven't updated any of my projects yet, but mine are usually based on Nerves projects, so if they are working then I'm sure it's great.
