### ISSUE TITLE
erts_dir not found in some cases

### ISSUE THREAD

**Issue by riverrun** [elixir-lang/elixir_make#29]
[This issue](https://github.com/riverrun/argon2_elixir/issues/29) was opened yesterday. It seems that in some cases, line 247 - `[erts_dir] = Path.wildcard(Path.join(root_dir, "erts*"))`- is returning an empty list, and that is resulting in an error.

**Comment by josevalim** [comment]
This is supposedly fixed by #28.

**Comment by riverrun** [comment]
Nice one! Thanks for the speedy resolution.
