### ISSUE TITLE
Makefile being used instead of Makefile.win

### ISSUE THREAD

**Issue by shini-tm** [elixir-lang/elixir_make#31]
For a Phoenix project, when trying to add dependencies such as `argon2_elixir` or `bcrypt_elixir`. The user is prompted to set the `MAKE` environment variable to the path of "nmake.exe" which requires installing the latest visual studio (or using chocolatey to install `VisualCppBuildTools`).

Compiling the project leads to an error:
```
makefile(34) : fatal error U1000: syntax error : ')' missing in macro invocation
Stop.
```
For bcrypt_elixir, the error is the same except for `makefile(34)`; instead it's `makefile(3)` (or some other single digit number). 

I was told this is probably happening because It's probably not checking if the executable specified by `MAKE` has the filename 'nmake' or 'nmake.exe' regardless of directory, instead of simply comparing against the string 'nmake'. and to report this bug. (kudos to legoscia on https://stackoverflow.com/questions/55616187/nmake-fails-when-attempting-to-compile-argon2-elixir)

**Comment by josevalim** [comment]
@shini-tm thank you for the report. I believe temporarily you can set the PATH to "nmake", without the ".exe". Would that fix your issue?
