### ISSUE TITLE
Not enough check for copying priv directory (bug?)

### ISSUE THREAD

**Issue by Eiji7** [elixir-lang/elixir_make#33]
Hey, I'm not sure if you would verify it as `bug` or `feature`, but in one specific case it looks like a `bug`, so it's why I wanted to describe it here.

In boydm/scenic_driver_glfw#26 we have an edge-case while using `elixir_make`. The problem is that we already have there a `priv` directory (with included `fonts` directory), so your `if` would always return `false` for our use case:

https://github.com/elixir-lang/elixir_make/blob/c8285de328033e3619b7fdb6be37163678bc9757/lib/mix/tasks/compile.make.ex#L130

Immediately I got some ideas. Some better and some not. I would like to describe well all of them in order to show my point of view:

1. Do not include `fonts`
If there is need for `hex` package then why we can't download "fonts"? **However** for other edge-cases it's not a real fix - it's **only** workaround. What if some project have important not-public images or other resources? Sure, it's still possible to download them, but for me it looks like overcomplication for me. Easier one is 2nd idea.

2. Store files in (let's say `priv-tmp`) and later copy them to `priv` using `Makefile`/`Makefile.vim`
It's again workaround, but really easy to introduce.

3. Always structure priv
Probably simplest idea. Just forgot about checking everything and simply always run that call. Of course it's good only in it's simplicity. The `if` is there only for a "bad joke".

4. Dynamically build `priv` directory list
This is my favorite one. It's easiest for developer as it does not requires to do anything. Finally it's idea which does not looks like a workaround.

5. Create a new dependency for 5th point
Well … It does not requires to change code here, but is it really worth to create a standalone dependency for such simple feature?

Maybe you would ask why not adding our own custom compiler task for just restructuring build directory. Here are 2 main reasons:
1. Possibly (i.e. in theory) long list of compilers added to app. When programming I'm thinking of future - no matter how far. If possible just don't cause problems (even only theoretical - it's because history already show how things changes rapidly).

2. Problem with testing - we need to compile before we can call our own mix compiler task (otherwise mix does not see it) and we need mix compiler task before compile, so here we go again to point 5th (create extra dependency).

**Optional idea**: If we would go for comparing list of files then maybe it's also good idea to consider ensuring checksum for files in `priv` directory?

Which idea you see best? What do you think about it? Is it worth to add support for checksum?

While it's problem of `scenic_driver_glfw` I believe it's not that bad idea to discuss it here as other developers could also hit such edge-case. As said from my point of view it looks like a `bug`, but contributors of this project could not agree with me.

ping @axelson, @boydm, @josevalim and @whatyouhide

**Comment by josevalim** [comment]
@Eiji7 you can see #32 for the whole discussion.

The preferred solution is 2. Keep fonts in a `fonts/` directory and copy it INSIDE the build priv (not the project priv). This is the approach that will work if the top project will have build embedded true or false.

**Comment by Eiji7** [comment]
Thanks, makes sense
