### ISSUE TITLE
Error or warning if project path contains space

### ISSUE THREAD

**Issue by LostKobrakai** [elixir-lang/elixir_make#34]
I recently reported this issue for muontrap failing when built in a project, which had a space in a folder of the absolute path: https://github.com/fhunleth/muontrap/issues/21. @fhunleth suggested adding a warning to this project instead of muontrap, as it's relevant to `make` in general.

**Comment by whatyouhide** [comment]
Probably a good call out. You interested in making a PR @LostKobrakai, or prefer me to take care of it? :)

**Comment by LostKobrakai** [comment]
If you could take a shot at it would be great.
