### ISSUE TITLE
Release 0.6.1

### ISSUE THREAD

**Issue by rinpatch** [elixir-lang/elixir_make#39]
NetBSD is one of the platforms [our project](https://git.pleroma.social/pleroma/pleroma) supports, so we would appreciate having a released version of `elixir_make` that works with it (this commit is needed: https://github.com/elixir-lang/elixir_make/commit/b46a5e82d3b3e78e180aedbd6f45ff970679a195)

**Comment by whatyouhide** [comment]
[Done](https://hex.pm/packages/elixir_make/0.6.1)! Thanks for the report :)
