### ISSUE TITLE
Question about where the so / dll file should be stored

### ISSUE THREAD

**Issue by riverrun** [elixir-lang/elixir_make#4]
With several projects that use NIFs, the so / dll file is stored in the `priv` directory. This raises the following question(s):

- If this is the standard place to store the file(s) created, do we want to create the `priv` directory if it is not there?
- Alternatively, do we want to add something to the documentation saying that the developer might need to create an empty `priv` directory as part of the package?

**Comment by josevalim** [comment]
The makefile can create the directory. An empty priv  should not be needed
given this compiler calls build_structure after invoking make. Thoughts?

On Tuesday, May 24, 2016, David Whitlock <notifications@github.com> wrote:

> With several projects that use NIFs, the so / dll file is stored in the
> priv directory. This raises the following question(s):
>
>    - If this is the standard place to store the file(s) created, do we
>    want to create the priv directory if it is not there?
>    - Alternatively, do we want to add something to the documentation
>    saying that the developer might need to create an empty priv directory
>    as part of the package?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir_make/issues/4>
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by riverrun** [comment]
You're right. I had forgotten that the makefile could handle this :)
