### ISSUE TITLE
[Proposal] Add a feature to put Makefile in Application.app_dir

### ISSUE THREAD

**Issue by zacky1972** [elixir-lang/elixir_make#41]
Hi, 

I propose Add a feature to put `Makefile` in `Application.app_dir(:app, "somewhere") `, especially in case that the Makefile is generated by a macro, e.g. in case of Pelemay.

The following error occurs by setting `:make_makefile` to `Applicatoin.app_dir(:app, "somewhere/Makefile")` in `project` in `mix.exs`:

```bash
❯❯❯ mix deps.get
** (ArgumentError) unknown application: :elixir_make_test
    (elixir 1.11.2) lib/application.ex:896: Application.app_dir/1
    (elixir 1.11.2) lib/application.ex:923: Application.app_dir/2
    mix.exs:11: ElixirMakeTest.MixProject.project/0
    (mix 1.11.2) lib/mix/project.ex:790: Mix.Project.get_project_config/1
    (mix 1.11.2) lib/mix/project.ex:114: Mix.Project.push/3
    (stdlib 3.13.2) lists.erl:1267: :lists.foldl/3
```

**Comment by josevalim** [comment]
Unfortunately we can't make that work because of a chicken and egg issue. When we are loading the mix.exs file, the application has not been defined nor compiled yet, so we can't access such paths. :(

**Comment by zacky1972** [comment]
I see. Thanks.

**Comment by zacky1972** [comment]
Excuse me,

I guess `:code.priv_dir(:my_app)` can be used instead of `Application.app_dir(:my_app, "somewhere")`.
So, I propose an alternative approach that uses `:code.priv_dir(:my_app)`, again.

**Comment by josevalim** [comment]
Application.app_dir uses :code.priv_dir, so that would have the same issue as above!

**Comment by zacky1972** [comment]
@josevalim I guess it won't work if you write `:code.priv_dir` and/or `Application.app_dir` in `mix.exs`, while it will work if you write them in `Mix.Tasks.*`. 
So, it will work by describing `mix.exs` using an optional switch: `in_priv_dir: true`.

**Comment by josevalim** [comment]
We could make the directory customizable, and then you can pass whatever you want. I can get behind that. :)
