### ISSUE TITLE
[Proposal] Add a feature building after executing a macro

### ISSUE THREAD

**Issue by zacky1972** [elixir-lang/elixir_make#43]
Hi,

Current Pelemay builds native code by calling make from itself after generating code and Makefile by a macro. If `elixir_make` will support a feature building after executing a macro, Pelemay can use it.

I'd like to contribute enhancement of `elixir_make`.

**Comment by josevalim** [comment]
@zacky1972 if I understand correctly, do you want to call `elixir_make` programmatically instead of via the mix.exs file? If so, an API that does so would be welcome, we can probably have it in the `ElixirMake` module, but it cannot call any functions from `Mix`.

**Comment by zacky1972** [comment]
Exactly. I didn't understand how to achieve such a function when I implemented Pelemay.

**Comment by whatyouhide** [comment]
A PR would be more than welcome @zacky1972. Let us know if you need any guidance, otherwise what @josevalim proposed sounds good :)
