### ISSUE TITLE
Apple Silicon Erlang not compiling bcrypt_elixir

### ISSUE THREAD

**Issue by wallyfoo** [elixir-lang/elixir_make#46]
I was using asdf to install the latest Apple Silicon compiled versions of Erlang and Elixir to use on a Phoenix project that employs the new gen-auth stuff.

When running elixir 1.11.2-otp-23 + Erlang 23.2.1 for Apple Silicon, bcrypt_elixir fails to compile, noting it needs Erlang 20 or better. The bcrypt.nif never gets created.

When I revert back to my last Intel version of Erlang, 23.0.3, I can rebuild the project and the bcrypt.nif gets created. Keeping Apple or Intel Elixir makes no difference. It comes down to the Erlang base system.

As for my project, I'll keep running the Intel Erlang for the time being. It works.

The maintainer of bcrypt_elixir suggested I seek input over here. It seems like an issue with elixir_make could possibly be adjusted to address apple silicon? I'm honestly not sure; I admit I’m still a newbie in this ecosystem, so I’m at a roadblock for where to go to seek the knowledge to get this resolved. I imagine this could eventually come to bite others.

**Comment by josevalim** [comment]
Hi @wallyfoo, we will be glad to take a look at it.  Can you please post your full stacktrace and error message when you try to compile? I want to assess from where the error is coming form. :) Thank you!

**Comment by wojtekmach** [comment]
I tested this on M1 on Elixir master & OTP-23.2.1 (both compiled from source) and it works for me. Please paste your stack traces and I'm happy to assist.

**Comment by fhunleth** [comment]
Hi! I just looked at bcrypt_elixir's Makefile and it saves its output to the source directory. Here's what I think is happening:

1. A build is run in Intel emulation mode. Intel shared library is made successfully.
2. Switch to Apple Silicon mode
3. Build is run, but the shared library doesn't load since it's the wrong kind. This looks like the error posted at https://github.com/riverrun/bcrypt_elixir/issues/29

This would be consistent with it working for @wojtekmach especially if he isn't switching back and forth.

I'll work on a PR for bcrypt_elixir to store its output to `_build`. This won't make this completely painless, since you'll still need to erase the `_build` directory when switching Intel/Apple` modes.

@wallyfoo Could you confirm this theory? If you switch to Apple mode and build completely clean (erase your _build and deps directories completely), I think that it will work for you.

**Comment by wallyfoo** [comment]
@fhunleth 

I may be in the wrong place. As I poke around the edges, I'm not sure where this error originates at all now.

Right now, I'm running macOS 11.1. 16GB M1 mini.

To create this error I took the following steps:

Erlang + Elixir installed from asdf latest. 1.11.2-otp-23 + 23.2.1

I deleted deps and _build.

mix deps.get

mix phx.server

The build phase reports bcrypt_elixir is fine:

```
==> bcrypt_elixir
make: Nothing to be done for 'all'.
Compiling 3 files (.ex)
Generated bcrypt_elixir app
```

When I get to the web interface and try to log in or register, Phoenix throws a wobbly.

```
[error] Process #PID<0.5988.0> raised an exception
** (RuntimeError) An error occurred when loading Bcrypt.
Make sure you have a C compiler and Erlang 20 installed.
If you are not using Erlang 20, either upgrade to Erlang 20 or
use version 0.12 of bcrypt_elixir.
See the Comeonin wiki for more information.

    (bcrypt_elixir 2.2.0) lib/bcrypt/base.ex:17: Bcrypt.Base.init/0
    (kernel 7.2) code_server.erl:1355: anonymous fn/1 in :code_server.handle_on_load/5
[warn] The on_load function for module Elixir.Bcrypt.Base returned:
{%RuntimeError{
   message: "An error occurred when loading Bcrypt.\nMake sure you have a C compiler and Erlang 20 installed.\nIf you are not using Erlang 20, either upgrade to Erlang 20 or\nuse version 0.12 of bcrypt_elixir.\nSee the Comeonin wiki for more information.\n"
 },
 [
   {Bcrypt.Base, :init, 0, [file: 'lib/bcrypt/base.ex', line: 17]},
   {:code_server, :"-handle_on_load/5-fun-0-", 1,
    [file: 'code_server.erl', line: 1355]}
 ]}

[error] Process #PID<0.5990.0> raised an exception
** (RuntimeError) An error occurred when loading Bcrypt.
Make sure you have a C compiler and Erlang 20 installed.
If you are not using Erlang 20, either upgrade to Erlang 20 or
use version 0.12 of bcrypt_elixir.
See the Comeonin wiki for more information.

    (bcrypt_elixir 2.2.0) lib/bcrypt/base.ex:17: Bcrypt.Base.init/0
    (kernel 7.2) code_server.erl:1355: anonymous fn/1 in :code_server.handle_on_load/5
[warn] The on_load function for module Elixir.Bcrypt.Base returned:
{%RuntimeError{
   message: "An error occurred when loading Bcrypt.\nMake sure you have a C compiler and Erlang 20 installed.\nIf you are not using Erlang 20, either upgrade to Erlang 20 or\nuse version 0.12 of bcrypt_elixir.\nSee the Comeonin wiki for more information.\n"
 },
 [
   {Bcrypt.Base, :init, 0, [file: 'lib/bcrypt/base.ex', line: 17]},
   {:code_server, :"-handle_on_load/5-fun-0-", 1,
    [file: 'code_server.erl', line: 1355]}
 ]}

[info] Sent 500 in 343ms
[error] #PID<0.5982.0> running RconliveWeb.Endpoint (connection #PID<0.5908.0>, stream id 13) terminated
Server: localhost:4000 (http)
Request: POST /users/log_in
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function Bcrypt.Base.checkpass_nif/2 is undefined (module Bcrypt.Base is not available)
        (bcrypt_elixir 2.2.0) Bcrypt.Base.checkpass_nif('xygreb-jyhRi6-moxsag', '$2b$12$YxCC2Oekil3HdM2gAZYoteHOZjEb8FJ6sGHHZXqvKpe4WAY/kaHcW')
        (bcrypt_elixir 2.2.0) lib/bcrypt.ex:111: Bcrypt.verify_pass/2
        (rconlive 0.1.0) lib/rconlive/accounts.ex:43: Rconlive.Accounts.get_user_by_email_and_password/2
        (rconlive 0.1.0) lib/rconlive_web/controllers/user_session_controller.ex:14: RconliveWeb.UserSessionController.create/2
        (rconlive 0.1.0) lib/rconlive_web/controllers/user_session_controller.ex:1: RconliveWeb.UserSessionController.action/2
        (rconlive 0.1.0) lib/rconlive_web/controllers/user_session_controller.ex:1: RconliveWeb.UserSessionController.phoenix_controller_pipeline/2
        (phoenix 1.5.7) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (rconlive 0.1.0) lib/rconlive_web/endpoint.ex:1: RconliveWeb.Endpoint.plug_builder_call/2
        (rconlive 0.1.0) lib/plug/debugger.ex:132: RconliveWeb.Endpoint."call (overridable 3)"/2
        (rconlive 0.1.0) lib/rconlive_web/endpoint.ex:1: RconliveWeb.Endpoint.call/2
        (phoenix 1.5.7) lib/phoenix/endpoint/cowboy2_handler.ex:65: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy 2.8.0) /Users/kit/Documents/Dev/rconline.nosync/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.8.0) /Users/kit/Documents/Dev/rconline.nosync/deps/cowboy/src/cowboy_stream_h.erl:300: :cowboy_stream_h.execute/3
        (cowboy 2.8.0) /Users/kit/Documents/Dev/rconline.nosync/deps/cowboy/src/cowboy_stream_h.erl:291: :cowboy_stream_h.request_process/3
        (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

This comeonin error (Erlang 20) has been reported here and there, but I couldn't find anything relevant to M1 builds. But since the build phase doesn't report a stack trace, I realize I may be in the wrong place. I am really happy to learn, however. Where does this error belong?

**Comment by fhunleth** [comment]
In your output, it doesn't look like the shared library rebuilt:

```
==> bcrypt_elixir
make: Nothing to be done for 'all'.
```

It should have looked something like:

```
==> bcrypt_elixir
mkdir -p priv
cc -g -O3 -Wall -Wno-format-truncation -I"/home/fhunleth/.asdf/installs/erlang/23.2.1/erts-11.1.5/include" -Ic_src -fPIC -shared  c_src/bcrypt_nif.c c_src/blowfish.c -o priv/bcrypt_nif.so
Compiling 3 files (.ex)
Generated bcrypt_elixir app
```

The `bcrypt_nif.so` file is what I'd like to see rebuilt. I don't have an Apple M1, but I wonder if running `file bcrypt_nif.so` would report whether it's an Intel or ARM shared library. The main thing I want to verify is that you're using an appropriate shared library.

**Comment by wallyfoo** [comment]
> The `bcrypt_nif.so` file is what I'd like to see rebuilt. I don't have an Apple M1, but I wonder if running `file bcrypt_nif.so` would report whether it's an Intel or ARM shared library. The main thing I want to verify is that you're using an appropriate shared library.

`rm -fr _build deps` again resulted in a proper rebuild.

**Comment by wallyfoo** [comment]
I think I figured it out! This is a VSCode issue! Again, I'm sorry for not understanding what was going on, but I wanted to share in case someone else has a brain fart like I did.

**Comment by fhunleth** [comment]
@wallyfoo You didn't waste anyone's time. Many Elixir libraries, but especially the ones that have been around a long time, build NIFs to their source directories. Most of the time it works, but when it doesn't, the error messages inevitably cause confusion. I'm 100% sure someone else will run into this again and will be helped by your reports. 

For reference, here's a link to the [bcrypt_elixir PR](https://github.com/riverrun/bcrypt_elixir/pull/30) to change the NIF output location.
