### ISSUE TITLE
Add NIF/Port guidelines

### ISSUE THREAD

**Issue by michalmuskala** [elixir-lang/elixir_make#8]
This project can be a great place to document best practices for writing NIFs and add some helper functions to do so.

I think the first, and most important part, is where to store the compiled artifacts and how to load them.

It could be a good idea as well to provide a function to load NIFs from the advised location or find the port executable. This would help with further standardization of how elixir handles NIFs/Ports.

**Comment by whatyouhide** [comment]
@michalmuskala I agree with all the standardization/best practices/guides concerns, but I'm not sure this is the right place to do so. `elixir_make` is just a compiler that runs make; it doesn't even have to be related to NIFs.

I am not sure about the alternatives though; where would we have such guide and documents? Or these helper functions?

**Comment by michalmuskala** [comment]
That's true it doesn't have to be related to NIFs, but if someone asks me how to write a NIF I will tell them to look at this repo - you just include the compiler, write a makefile and that's it. Much simpler than figuring it all out on your own.

It would even make sense to provide a simple NIF generator 
`mix make.gen.nif MyApp.Module function/2 other_function/3`
But I'm not sure that's a good idea - you probably should read a lot before using a nif, so it shouldn't be too simple.

**Comment by whatyouhide** [comment]
@michalmuskala yes, that's my point. Also, a **huge** point to keep in mind in my opinion is that NIFs in C have just more literature and are more common but they're not the only kind of NIFs: you can write NIFs with pretty much anything, e.g., Rust is becoming a pretty solid choice or maybe OCaml. So generating a C NIFs template is not something I'm a fan of 😕

**Comment by riverrun** [comment]
I agree that we need more information somewhere. I was going to suggest adding something to the Elixir website - with guides, example Makefiles, etc. I know there's already an 'Interoperability with C' guide, but it could be easier to find, and it needs updating.

**Comment by whatyouhide** [comment]
I definitely think this belongs much more in Elixir's wiki than here. I should update http://andrealeopardi.com/posts/using-c-from-elixir-with-nifs/ as well 😄

@michalmuskala I'm gonna close this one for now, feel free to reopen if you have more feedback on this since it's definitely valuable feedback!
