### ISSUE TITLE
Release v0.8.4

### ISSUE THREAD

**Issue by mneumann** [elixir-lang/elixir_make#86]
which includes DragonFly support. That makes my life easier :)

**Comment by cocoa-xu** [comment]
Hi @mneumann, sorry I don't have the permission on hex.pm to release new versions for `elixir_make`. But I remember that the default make executable can be changed by setting environment variable `MAKE` to `gmake`. It might help, but if it doesn't, I'm also curious that if you could perhaps share which part(s) it breaks. :)

**Comment by mneumann** [comment]
@cocoa-xu Thanks! Yes, using MAKE=gmake works - I just forget it sometimes, so still hoping that one day it "just works" :)
