### ISSUE TITLE
Add MAKE_EXECUTABLE environment variable?

### ISSUE THREAD

**Issue by riverrun** [elixir-lang/elixir_make#9]
I know this was discussed on the original 'make' pull request thread (in the main elixir repo), but it was unclear what conclusions people had reached.
Anyway, this proposal is to add support to define a different 'make' program if the environment variable `MAKE_EXECUTABLE` is set, thereby giving the user more freedom to customize the build.
If there's any interest, I can send a PR.

**Comment by josevalim** [comment]
Thanks @riverrun! That sounds like a good plan although it seems the best option is to support `$MAKE` rather than `$MAKE_EXECUTABLE`. See: https://github.com/elixir-lang/elixir/issues/4082#issuecomment-223659195

**Comment by whatyouhide** [comment]
@riverrun you're very welcome to open a PR, thanks a lot 💟 :)

**Comment by whatyouhide** [comment]
Closed by #11.
